Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Security.Claims;
using FreelanceFusion.Models;

namespace FreelanceFusion.Controllers
{
    public class DashboardController : Controller
    {
        private readonly string _connectionString = "Server=(localdb)\\MylocalDB;Database=FreelanceFusion;Trusted_Connection=True;MultipleActiveResultSets=True";

        private int GetCurrentUserId()
        {
            var claimsIdentity = HttpContext.User.Identity as ClaimsIdentity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (int.TryParse(userId, out int id))
            {
                return id;
            }
            else
            {
                throw new Exception("Current user ID not found or invalid.");
            }
        }

        public IActionResult ClientView()
        {
            var jobs = GetJobsForCurrentUser();
            var bids = GetBidsForCurrentUser();
            ViewBag.ShowButtons = true;

            return View((jobs, bids));
        }

        public IActionResult FreelancerView()
        {
            var bids = GetBidsMadeByCurrentUser();
            ViewBag.ShowButtons = false;
            return View(bids);
        }


        private List<Job> GetJobsForCurrentUser()
        {
            List<Job> jobs = new List<Job>();
            using (SqlConnection connection = new SqlConnection(_connectionString))
            {
                string sql = "SELECT * FROM job j  JOIN [user] u  ON j.UserID = u.UserID where j.UserID = @UserId";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@UserId", GetCurrentUserId());
                    connection.Open();
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Job job = new Job
                            {
                                JobID = (int)reader["JobId"],
                                Title = reader["Title"].ToString(),
                                Budget = reader["Budget"].ToString(),
                                PostedDate = reader["PostedDate"].ToString(),
                                Deadline = reader["Deadline"].ToString(),
                                FirstName = reader["FirstName"].ToString(),
                                LastName = reader["LastName"].ToString()
                            };
                            jobs.Add(job);
                        }
                    }
                }
            }
            return jobs;
        }

        private List<Bid> GetBidsForCurrentUser()
        {
            List<Bid> bids = new List<Bid>();
            using (SqlConnection connection = new SqlConnection(_connectionString))
            {
                string sql = "SELECT b.BidID, b.IsAWarded, b.JobID, b.BidAmount, b.BidMessage, b.BidDate, j.Title, u.FirstName, u.LastName FROM Bid b JOIN Job j ON b.JobID = j.JobID JOIN [User] u ON b.UserID = u.UserID where j.UserID=@UserId";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@UserId", GetCurrentUserId());
                    connection.Open();
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Bid bid = new Bid
                            {
                                BidID = (int)reader["BidID"],
                                BidStatus = reader["IsAwarded"].ToString(),
                                BidAmount = reader["BidAmount"].ToString(),
                                BidMessage = reader["BidMessage"].ToString(),
                                BidDate = reader["BidDate"].ToString(),
                                JobTitle = reader["Title"].ToString(),
                                FirstName = reader["FirstName"].ToString(),
                                LastName = reader["LastName"].ToString(),
                                JobID = reader["JobID"].ToString(),
                            };
                            bids.Add(bid);
                        }
                    }
                }
            }
            return bids;
        }


        private List<Bid> GetBidsMadeByCurrentUser()
        {
            List<Bid> bids = new List<Bid>();
            using (SqlConnection connection = new SqlConnection(_connectionString))
            {
                string sql = "SELECT b.BidID, b.IsAWarded, b.JobID, b.BidAmount, b.BidMessage, b.BidDate, j.Title, u.FirstName, u.LastName FROM Bid b JOIN Job j ON b.JobID = j.JobID JOIN [User] u ON b.UserID = u.UserID where b.UserID=@UserId";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@UserId", GetCurrentUserId());
                    connection.Open();
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Bid bid = new Bid
                            {
                                BidID = (int)reader["BidID"],
                                BidStatus = reader["IsAwarded"].ToString(),
                                BidAmount = reader["BidAmount"].ToString(),
                                BidMessage = reader["BidMessage"].ToString(),
                                BidDate = reader["BidDate"].ToString(),
                                JobTitle = reader["Title"].ToString(),
                                FirstName = reader["FirstName"].ToString(),
                                LastName = reader["LastName"].ToString(),
                                JobID = reader["JobID"].ToString(),
                            };
                            bids.Add(bid);
                        }
                    }
                }
            }
            return bids;
        }

        public IActionResult DeleteJob(int jobId)
        {
            try
            {
                using (SqlConnection connection = new SqlConnection(_connectionString))
                {
                    connection.Open();
                    string sql = "DELETE FROM job WHERE JobID = @JobID";
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.Parameters.AddWithValue("@JobID", jobId);
                        command.ExecuteNonQuery();
                    }
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error");
            }
            return RedirectToAction("FreelancerView");
        }
    }
}

Controllers/JoblistingController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using FreelanceFusion.Models;
using System.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Linq;

namespace FreelanceFusion.Controllers
{
    public class JoblistingController : Controller
    {
        private readonly string connectionString = "Server=(localdb)\\MylocalDB;Database=FreelanceFusion;Trusted_Connection=True;MultipleActiveResultSets=True";

        public IActionResult Index(string searchQuery)
        {
            List<Job> jobs = GetJobsFromDatabase();
            if (!string.IsNullOrEmpty(searchQuery))
            {
                jobs = jobs.Where(j => j.Title.ToLower().Contains(searchQuery.ToLower())).ToList();
            }

            if (jobs.Count == 0)
            {
                ViewBag.Message = "No jobs found matching the search query.";
            }
            return View(jobs);
        }

        private List<Job> GetJobsFromDatabase()
        {
            List<Job> jobs = new List<Job>();
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                string sql = "select j.jobID, j.title, j.budget, j.experience, j.Description, u.FirstName, u.LastName from job j join [user] u on j.UserID=u.UserID";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    connection.Open();
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Job job = new Job
                            {
                                JobID = Convert.ToInt32(reader["jobID"]),
                                Title = reader["title"].ToString(),
                                Budget = reader["budget"].ToString(),
                                Experience = reader["Experience"].ToString(),
                                FirstName = reader["FirstName"].ToString(),
                                LastName = reader["LastName"].ToString(),
                                Description = reader["Description"].ToString(),
                            };
                            jobs.Add(job);
                        }
                    }
                }
            }
            return jobs;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using FreelanceFusion.Models; // Or your namespace for the UserCredentials model


namespace FreelanceFusion.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;

        // public bool IsLoggedIn { get; set; }

        public LoginController(ILogger<LoginController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
       
        public async Task<IActionResult> Authentication(UserCredentials credentials)
        {
            string connectionString = "Server=(localdb)\\MylocalDB;Database=FreelanceFusion;Trusted_Connection=True;MultipleActiveResultSets=True"; // Replace with your connection string

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                string query = "SELECT UserID FROM [User] WHERE Username = @Username AND Password = @Password";
                SqlCommand command = new SqlCommand(query, connection);
                command.Parameters.AddWithValue("@Username", credentials.Username);
                command.Parameters.AddWithValue("@Password", credentials.Password);

                int UserID = Convert.ToInt32(command.ExecuteScalar());

                if (UserID > 0)
            {
                
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, credentials.Username),
                 new Claim(ClaimTypes.NameIdentifier, UserID.ToString()),
                 new Claim("Password", credentials.Password)
                
            };

            var claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity));

            return RedirectToAction("Index", "Home");
        }
                else
                {
                    // Authentication failed, return the login view with an error message
                     ModelState.AddModelError(string.Empty, "Invalid username or password.");
                    return View("Index");
                }
            }
        }

       
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Html
@using Microsoft.AspNetCore.Mvc.Rendering


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FreelanceFusion</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FreelanceFusion.styles.css" asp-append-version="true" />

    <style>
     .profile{
        width: 138px;   
        text-align: center; 
        color: #338573; 
        font-size: 20px; 
        font-family: Noto Sans; 
        font-weight: 600; 
        text-decoration: none;
        word-wrap: break-word
     }
     a.profile:hover{
        color:inherit
     }
     .dash{
        width: 138px; 
        margin-right:20px;
        text-align: center; 
        color: #338573; 
        font-size: 20px; 
        font-family: Noto Sans; 
        font-weight: 600; 
        text-decoration: none;
        word-wrap: break-word"
     }
     a.dash:hover{
        color:inherit
     }
     
    .postjob{
       width: 126px; 
       height: 38px; 
       text-align: center;
       color: white; 
       font-size: 24px; 
       font-family: Noto Sans; 
       font-weight: 700; 
       word-wrap: break-word;
       text-decoration: none;
       justify-content:center
    }
    a.postjob:hover{
        color:inherit
     }
    .login{
        width: 138px; 
        margin-right:20px;
        text-align: center; 
        color: #338573; 
        font-size: 20px; 
        font-family: Noto Sans; 
        font-weight: 600; 
        text-decoration: none;
        word-wrap: break-word"
     }
     a.login:hover{
        color:inherit
     }
      .joblisting{
        width: 138px; 
        margin-right:20px;
        text-align: center; 
        color: #338573; 
        font-size: 20px; 
        font-family: Noto Sans; 
        font-weight: 600; 
        text-decoration: none;
        word-wrap: break-word"
     }
     a.joblisting:hover{
        color:inherit
     }
     .logout{
        width: 138px; 
        margin-right:20px;
        text-align: center; 
        color: #338573; 
        font-size: 20px; 
        font-family: Noto Sans; 
        font-weight: 600; 
        text-decoration: none;
        word-wrap: break-word"
     }
     a.logout:hover{
        color:inherit
     }
     .signup{
        width: 138px; 
        margin-right:20px;
        text-align: center; 
        color: #338573; 
        font-size: 20px; 
        font-family: Noto Sans; 
        font-weight: 600; 
        text-decoration: none;
        word-wrap: break-word"
     }
     a.signup:hover{
        color:inherit
     }
     .logo{
        width: 210px; 
        text-align: center; 
        color: #338573; 
        font-size: 30px; 
        font-family: Noto Sans; 
        font-weight: 600; 
        text-decoration: none;
        word-wrap: break-word"
     }
     a.logo:hover{
        color:inherit
     }
    .header{
      top:0;
        position:fixed;
        z-index:10;
        background-color: transparent;
        width:100vw;
        transition: background-color 0.3s;
        
    }
    .header.transparent {
            background-color: transparent;
        }

        .header.scrolled {
            background-color: white;
        }
    .footer{
      bottom:0
        position:fixed;
        z-index:100;
        width:100vw;  
    }
    </style>

</head>
<body>
    @await Html.PartialAsync("_NavigationBar")



    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

       <script>
        window.addEventListener('scroll', function() {
            const header = document.querySelector('.header');
            const scrolled = window.scrollY > 0;
            if (scrolled) {
                header.classList.add('scrolled');
                header.classList.remove('transparent');
            } else {
                header.classList.add('transparent');
                header.classList.remove('scrolled');
            }
        });
    </script>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_NavigationBar.cshtml
@using Microsoft.AspNetCore.Authentication.Cookies

@{
    var isAuthenticated = User.Identity.IsAuthenticated;
}

<header class="header">
    <nav class="navbar  navbar-expand-sm navbar-toggleable-sm navbar-light ">
        <div class="container-fluid">
            <a class=" logo" asp-area="" asp-controller="Home" asp-action="Index">FreelanceFusion</a>

            <div class="navbar-collapse collapse justify-content-end">
                <ul class="navbar-nav text-align-center">
                    @if (isAuthenticated)
                    {    
                         <li class="nav-item">
                            <a class="logout" asp-area="" asp-controller="LogOut" asp-action="Index">LogOut</a>
                        </li>
                        <li class="nav-item">
                            <a class="joblisting" asp-area="" asp-controller="Joblisting" asp-action="Index">JobListing</a>
                        </li>
                        <button style="width: 120px; height: 40px; background: #338573; border-radius: 10px; text-align:center; margin-right:20px">
                            <li class="nav-item">
                                <a class="postjob" asp-area="" asp-controller="PostJob" asp-action="PostJob">PostJob</a>
                            </li>
                        </button>
                        <li class="nav-item">
                            <a class="dash" asp-area="" asp-controller="Dashboard" asp-action="ClientView">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="profile" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a>
                        </li> 
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="signup" asp-area="" asp-controller="SignUp" asp-action="Index">SignUp</a>
                        </li>
                        <li class="nav-item">
                            <a class="login" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                       
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>