Controllers/BidDetailsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Security.Claims;
using FreelanceFusion.Models;

namespace FreelanceFusion.Controllers;

public class BidDetailsController : Controller
{    

      private CurrentUser GetCurrentLoggedInUser()
        {
            var claimsIdentity = HttpContext.User.Identity as ClaimsIdentity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (int.TryParse(userId, out int id))
            {
                return new CurrentUser { UserID = id };
            }
            else
            {
                // Handle the case where the user ID is not available or not in the expected format
                // For example, you can return a default user ID or throw an exception
                throw new Exception("Current user ID not found or invalid.");
            }
       }


    private readonly string connectionString = "Server=(localdb)\\MylocalDB;Database=FreelanceFusion;Trusted_Connection=True;MultipleActiveResultSets=True";
    public IActionResult Index(int BidID)
    {
        Bid bid = GetBidDetailsFromDatabase(BidID);
    
        if (bid == null)
        {
            return NotFound();
        }

        // int jobID = int.Parse(JobID);
          
        //   bool isBidAwarded = IsBidAwarded(jobID, BidID);
        //   ViewBag.IsBidAwarded = isBidAwarded;
        return View(bid);
    }

    public IActionResult Indexx(int BidID )
    {
        Bid bid = GetBidDetailsFromDatabase(BidID);
         CurrentUser currentUser = GetCurrentLoggedInUser();
             

        if (bid == null)
        {
            return NotFound();
        }

       

      
        return View(bid);
    }

    public IActionResult NotFound()
{
    return View();
}


    public Bid GetBidDetailsFromDatabase(int BidID)
    {
        Bid bid = new Bid();
        using (SqlConnection connection = new SqlConnection(connectionString))
        {
            string sql ="select * from bid join job on bid.JobID = job.JobID where BidID=@BidID";
            using (SqlCommand command = new SqlCommand(sql, connection))
            {
                command.Parameters.AddWithValue("@BidID", BidID);
                connection.Open();
                using (SqlDataReader reader = command.ExecuteReader())
                {
                    if (reader.Read())
                    {
                        bid.BidID = (int)reader["BidId"];
                        bid.BidAmount = reader["BidAmount"].ToString();
                        bid.BidMessage = reader["bidMessage"].ToString();
                        bid.BidDate = reader["bidDate"].ToString();
                        bid.JobTitle = reader["Title"].ToString();
                        bid.UserID =(int)reader["UserID"];
                        bid.JobID = reader ["JobID"].ToString();
                        bid.BidStatus = reader["IsAwarded"].ToString();
                        
                    }
                }
            }
        }
        return bid;
    }

       [HttpPost]
public IActionResult AcceptBid(int bidId, int jobId)
{
    // Update the bid status in the database to 1 for the provided bidId
    using (SqlConnection connection = new SqlConnection(connectionString))
    {
        connection.Open();
        string updateQuery = "UPDATE Bid SET IsAwarded = 1 WHERE BidID = @bidId";
        SqlCommand command = new SqlCommand(updateQuery, connection);
        command.Parameters.AddWithValue("@bidId", bidId);
        command.ExecuteNonQuery();
    }

    // Notify other bids with the same jobId
    using (SqlConnection connection = new SqlConnection(connectionString))
    {
        connection.Open();
        string notifyQuery = "UPDATE Bid SET IsAwarded = 2 WHERE JobID = @jobId AND IsAwarded = 0 AND BidID != @bidId";
        SqlCommand command = new SqlCommand(notifyQuery, connection);
        command.Parameters.AddWithValue("@jobId", jobId);
        command.Parameters.AddWithValue("@bidId", bidId);
        command.ExecuteNonQuery();
    }


    // // Set TempData message based on the bid status
    // if (IsBidAwarded(bidId, jobId))
    // {
    //     TempData["BidMessage"] = "Bid Awarded";
    // }
   

    return RedirectToAction("Index", new { bidId });
}
    

// private bool IsBidAwarded(int bidId, int jobId)
// {
//     using (SqlConnection connection = new SqlConnection(connectionString))
//     {
//         connection.Open();
//         string query = "SELECT IsAwarded FROM Bid WHERE BidID = @bidId AND JobID = @jobId";
//         SqlCommand command = new SqlCommand(query, connection);
//         command.Parameters.AddWithValue("@bidId", bidId);
//         command.Parameters.AddWithValue("@jobId", jobId);

//         using (SqlDataReader reader = command.ExecuteReader())
//         {
//             if (reader.Read())
//             {
//                 return Convert.ToBoolean(reader["IsAwarded"]);
//             }
//             else{
//                 return false; // if no records were found
//             }
//         }
//     }    



// }
}

Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Security.Claims;
using FreelanceFusion.Models;

namespace FreelanceFusion.Controllers
{
    public class DashboardController : Controller
    {
        private readonly string _connectionString = "Server=(localdb)\\MylocalDB;Database=FreelanceFusion;Trusted_Connection=True;MultipleActiveResultSets=True";

        private int GetCurrentUserId()
        {
            var claimsIdentity = HttpContext.User.Identity as ClaimsIdentity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (int.TryParse(userId, out int id))
            {
                return id;
            }
            else
            {
                throw new Exception("Current user ID not found or invalid.");
            }
        }

        public IActionResult ClientView()
        {
            var jobs = GetJobsForCurrentUser();
            var bids = GetBidsForCurrentUser();
            ViewBag.ShowButtons = true;

            return View((jobs, bids));
        }

        public IActionResult FreelancerView()
        {
            var bids = GetBidsMadeByCurrentUser();
            ViewBag.ShowButtons = false;
            return View(bids);
        }


        private List<Job> GetJobsForCurrentUser()
        {
            List<Job> jobs = new List<Job>();
            using (SqlConnection connection = new SqlConnection(_connectionString))
            {
                string sql = "SELECT * FROM job j  JOIN [user] u  ON j.UserID = u.UserID where j.UserID = @UserId";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@UserId", GetCurrentUserId());
                    connection.Open();
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Job job = new Job
                            {
                                JobID = (int)reader["JobId"],
                                Title = reader["Title"].ToString(),
                                Budget = reader["Budget"].ToString(),
                                PostedDate = reader["PostedDate"].ToString(),
                                Deadline = reader["Deadline"].ToString(),
                                FirstName = reader["FirstName"].ToString(),
                                LastName = reader["LastName"].ToString()
                            };
                            jobs.Add(job);
                        }
                    }
                }
            }
            return jobs;
        }

        private List<Bid> GetBidsForCurrentUser()
        {
            List<Bid> bids = new List<Bid>();
            using (SqlConnection connection = new SqlConnection(_connectionString))
            {
                string sql = "SELECT b.BidID, b.IsAWarded, b.JobID, b.BidAmount, b.BidMessage, b.BidDate, j.Title, u.FirstName, u.LastName FROM Bid b JOIN Job j ON b.JobID = j.JobID JOIN [User] u ON b.UserID = u.UserID where j.UserID=@UserId";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@UserId", GetCurrentUserId());
                    connection.Open();
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Bid bid = new Bid
                            {
                                BidID = (int)reader["BidID"],
                                BidStatus = reader["IsAwarded"].ToString(),
                                BidAmount = reader["BidAmount"].ToString(),
                                BidMessage = reader["BidMessage"].ToString(),
                                BidDate = reader["BidDate"].ToString(),
                                JobTitle = reader["Title"].ToString(),
                                FirstName = reader["FirstName"].ToString(),
                                LastName = reader["LastName"].ToString(),
                                JobID = reader["JobID"].ToString(),
                            };
                            bids.Add(bid);
                        }
                    }
                }
            }
            return bids;
        }


        private List<Bid> GetBidsMadeByCurrentUser()
        {
            List<Bid> bids = new List<Bid>();
            using (SqlConnection connection = new SqlConnection(_connectionString))
            {
                string sql = "SELECT b.BidID, b.IsAWarded, b.JobID, b.BidAmount, b.BidMessage, b.BidDate, j.Title, u.FirstName, u.LastName FROM Bid b JOIN Job j ON b.JobID = j.JobID JOIN [User] u ON b.UserID = u.UserID where b.UserID=@UserId";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@UserId", GetCurrentUserId());
                    connection.Open();
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Bid bid = new Bid
                            {
                                BidID = (int)reader["BidID"],
                                BidStatus = reader["IsAwarded"].ToString(),
                                BidAmount = reader["BidAmount"].ToString(),
                                BidMessage = reader["BidMessage"].ToString(),
                                BidDate = reader["BidDate"].ToString(),
                                JobTitle = reader["Title"].ToString(),
                                FirstName = reader["FirstName"].ToString(),
                                LastName = reader["LastName"].ToString(),
                                JobID = reader["JobID"].ToString(),
                            };
                            bids.Add(bid);
                        }
                    }
                }
            }
            return bids;
        }

        public IActionResult DeleteJob(int jobId)
        {
            try
            {
                using (SqlConnection connection = new SqlConnection(_connectionString))
                {
                    connection.Open();
                    string sql = "DELETE FROM job WHERE JobID = @JobID";
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.Parameters.AddWithValue("@JobID", jobId);
                        command.ExecuteNonQuery();
                    }
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error");
            }
            return RedirectToAction("FreelancerView");
        }
    }
}

Controllers/JobDetailsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Security.Claims;
using FreelanceFusion.Models;

namespace FreelanceFusion.Controllers;

public class JobDetailsController : Controller
{
   
    private CurrentUser GetCurrentLoggedInUser()
        {
            var claimsIdentity = HttpContext.User.Identity as ClaimsIdentity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (int.TryParse(userId, out int id))
            {
                return new CurrentUser { UserID = id };
            }
            else
            {
                // Handle the case where the user ID is not available or not in the expected format
                // For example, you can return a default user ID or throw an exception
                throw new Exception("Current user ID not found or invalid.");
            }
       }


    private readonly string connectionString = "Server=(localdb)\\MylocalDB;Database=FreelanceFusion;Trusted_Connection=True;MultipleActiveResultSets=True";
    public IActionResult Index(int JobID)
    {
        Job job = GetJobDetailsFromDatabase(JobID);
        CurrentUser currentUser = GetCurrentLoggedInUser();

        if (job == null)
        {
            return NotFound();
        }
        
        ViewBag.ShowButtons = job.UserID != currentUser.UserID;
        return View(job);
    }

    public IActionResult NotFound()
{
    return View();
}


    private Job GetJobDetailsFromDatabase(int JobID)
    {
        Job job = new Job();
        using (SqlConnection connection = new SqlConnection(connectionString))
        {
            string sql ="select * from job j join [user] u on j.UserID=u.UserID where j.JobID=@JobID";
            using (SqlCommand command = new SqlCommand(sql, connection))
            {
                command.Parameters.AddWithValue("@JobID", JobID);
                connection.Open();
                using (SqlDataReader reader = command.ExecuteReader())
                {
                    if (reader.Read())
                    {
                        job.JobID = (int)reader["JobId"];
                        job.Title = reader["Title"].ToString();
                        job.Description = reader["Description"].ToString();
                        job.Budget = reader["Budget"].ToString();
                        job.PostedDate = reader["PostedDate"].ToString();
                        job.Deadline = reader["Deadline"].ToString();
                        job.JobSkill = reader["JobSkill"].ToString();
                        job.Experience = reader["Experience"].ToString();
                        job.FirstName = reader["FirstName"].ToString();
                        job.LastName = reader["LastName"].ToString();
                        job.Email = reader["Email"].ToString();
                        job.UserID = (int)reader["UserID"];
                    }
                }
            }
        }
        return job;
    }
}

Views/Dashboard/ClientView.cshtml
@{
    ViewData["Title"] = "Freelancer Dashboard";
}

<!DOCTYPE html>
<html>
<head>
    <style>
        .table {
            width: 90%;
            margin: 0 auto;
            border-collapse: collapse;
            margin-bottom: 30px;
            border-radius:100px;
        }

        .table th, .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
           
        }

        .table th {
            background-color: #f2f2f2;
        }

        .table tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .table tr:hover {
            background-color: #f5f5f5;
        }

        .table a {
            padding: 6px 12px;
            border: 1px solid #;
            border-radius: 4px;
            background-color: #338573;
            color: #fff;
            text-decoration: none;
        }

        .table a:hover {
            background-color: #23527c;
            border-color: #23527c;
        }
    </style>
</head>
<body style ="background:#F8FAFC " >
    <a asp-controller="Dashboard" asp-action="FreelancerView" >
        <h1 style="width:187px;left: 60px; margin-top: 20px; text-align:center; border-radius:20px; position: absolute; background: #338573; color: white; font-size: 20px; font-family: Poppins; font-weight: 500; line-height: 50px; word-wrap: break-word">Client View</h1>
    </a>

    <h2 style="text-align: center; margin-top: 80px; font-size: 30px; font-family: Poppins; font-weight: 500; line-height: 80px; word-wrap: break-word">My Job List</h2>
<div style="width: 1200px; margin-left:80px; background:#fff; border-radius:16px; height: auto; flex-direction: column; justify-content: space-between; align-items: flex-start; gap: 16px; display: inline-flex">
    <div style="width: 1078px; margin-left:50px; margin-top:50px; background: #F8FAFC; border-radius: 12px; justify-content: space-between; align-items: flex-start; display: inline-flex">
        <div style="width: 340px; height: 64px; padding: 8px; justify-content: flex-start; align-items: center; gap: 16px; display: flex">
            <div style="flex: 1 1 0; color: #94A3B8; font-size: 16px; font-family: Inter; font-weight: 500; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">Title</div>
        </div>
        <div style="width: 180px; height: 64px; padding: 8px; justify-content: flex-start; align-items: center; gap: 16px; display: flex">
            <div style="flex: 1 1 0; color: #94A3B8; font-size: 16px; font-family: Inter; font-weight: 500; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">Posted Date</div>
        </div>
        <div style="width: 200px; height: 64px; padding: 8px; justify-content: flex-start; align-items: center; gap: 16px; display: flex">
            <div style="flex: 1 1 0; color: #94A3B8; font-size: 16px; font-family: Inter; font-weight: 500; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">Application Deadline</div>
        </div>
        <div style="width: 100px; height: 64px; padding: 8px; justify-content: flex-start; align-items: center; gap: 16px; display: flex">
            <div style="flex: 1 1 0; color: #94A3B8; font-size: 16px; font-family: Inter; font-weight: 500; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">Action</div>
        </div>
    </div>
    @foreach (var job in Model.Item1)
    {
        <div style="width: 1078px; margin-left:50px; background: #F8FAFC; border-radius: 12px; justify-content: space-between; align-items: flex-start; display: inline-flex">
            <div style="width: 340px;  height: 64px; padding: 8px; justify-content: space-between; align-items: center; gap: 16px; display: flex">
                <div style="flex: 1 1 0; color: #0F172A; font-size: 16px; font-family: Inter; font-weight: 600; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">@job.Title</div>
            </div>
            <div style="width: 180px; height: 64px; padding: 8px; justify-content: flex-start; align-items: center; gap: 16px; display: flex">
                <div style="flex: 1 1 0; color: #0F172A; font-size: 16px; font-family: Inter; font-weight: 600; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">@job.PostedDate</div>
            </div>
            <div style="width: 200px; height: 64px; padding: 8px; justify-content: flex-start; align-items: center; gap: 16px; display: flex">
                <div style="flex: 1 1 0; color: #0F172A; font-size: 16px; font-family: Inter; font-weight: 600; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">@job.Deadline</div>
            </div>
            <div style="width: 100px; height: 64px; padding: 8px; justify-content: flex-start; align-items: center; gap: 16px; display: flex">
                <div style="flex: 1 1 0; color: #0F172A; font-size: 16px; font-family: Inter; font-weight: 600; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">
                    <a asp-controller="JobDetails" asp-action="Index" asp-route-JobID="@job.JobID" style="text-decoration: none; color: #2563EB">View</a>
                </div>
            </div>
        </div>
        <div style="width: 1078px; height: 0px; border: 1px #fff solid"></div> 
    }
</div>

    <h2 style="text-align: center; font-size: 30px; font-family: Poppins; font-weight: 500; line-height: 80px; word-wrap: break-word">Job Bids</h2>
<div style="width: 1200px; margin-left:80px; height: auto; background:#fff; border-radius:16px; flex-direction: column; justify-content: space-between; align-items: flex-start; gap: 16px; display: inline-flex">
    <div style="width: 1078px; margin-left:50px; margin-top:50px; background: #F8FAFC; border-radius: 12px; justify-content: space-between; align-items: flex-start; display: inline-flex">
        <div style="width: 200px; height: 64px; padding: 8px; justify-content: flex-start; align-items: center; gap: 16px; display: flex">
            <div style="flex: 1 1 0; color: #94A3B8; font-size: 16px; font-family: Inter; font-weight: 500; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">Freelancer Name</div>
        </div>
        <div style="width: 240px; height: 64px; padding: 8px; justify-content: flex-start; align-items: center; gap: 16px; display: flex">
            <div style="flex: 1 1 0; color: #94A3B8; font-size: 16px; font-family: Inter; font-weight: 500; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">Job Title</div>
        </div>
        <div style="width: 160px; height: 64px; padding: 8px; justify-content: flex-start; align-items: center; gap: 16px; display: flex">
            <div style="flex: 1 1 0; color: #94A3B8; font-size: 16px; font-family: Inter; font-weight: 500; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">Bid Date</div>
        </div>
        <div style="width: 160px; height: 64px; padding: 8px; justify-content: flex-start; align-items: center; gap: 16px; display: flex">
            <div style="flex: 1 1 0; color: #94A3B8; font-size: 16px; font-family: Inter; font-weight: 500; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">Bid Amount</div>
        </div>
        <div style="width: 100px; height: 64px; padding: 8px; justify-content: flex-start; align-items: center; gap: 16px; display: flex">
            <div style="flex: 1 1 0; color: #94A3B8; font-size: 16px; font-family: Inter; font-weight: 500; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">Action</div>
        </div>
    </div>
    @foreach (var bid in Model.Item2)
    {
        <div style="width: 1078px; margin-left:50px; background: #F8FAFC; border-radius: 12px; justify-content: space-between; align-items: flex-start; display: inline-flex">
            <div style="width: 200px; height: 64px; padding: 8px; justify-content: space-between; align-items: center; gap: 16px; display: flex">
                <div style="flex: 1 1 0; color: #0F172A; font-size: 16px; font-family: Inter; font-weight: 600; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">@($"{bid.FirstName} {bid.LastName}")</div>
            </div>
            <div style="width: 240px; height: 64px; padding: 8px; justify-content: flex-start; align-items: center; gap: 16px; display: flex">
                <div style="flex: 1 1 0; color: #0F172A; font-size: 16px; font-family: Inter; font-weight: 600; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">@bid.JobTitle</div>
            </div>
            <div style="width: 180px; height: 64px; padding: 8px; justify-content: flex-start; align-items: center; gap: 16px; display: flex">
                <div style="flex: 1 1 0; color: #0F172A; font-size: 16px; font-family: Inter; font-weight: 600; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">@bid.BidDate</div>
            </div>
            <div style="width: 160px; height: 64px; padding: 8px; justify-content: flex-start; align-items: center; gap: 16px; display: flex">
                <div style="flex: 1 1 0; color: #0F172A; font-size: 16px; font-family: Inter; font-weight: 600; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">GH₵ @bid.BidAmount</div>
            </div>
            <div style="width: 100px; height: 64px; padding: 8px; justify-content: flex-start; align-items: center; gap: 16px; display: flex">
                <div style="flex: 1 1 0; color: #0F172A; font-size: 16px; font-family: Inter; font-weight: 600; line-height: 24px; letter-spacing: 0.20px; word-wrap: break-word">
                    <a asp-controller="BidDetails" asp-action="Index" asp-route-BidID="@bid.BidID" style="text-decoration: none; color: #2563EB">View</a>
                </div>
            </div>
        </div>
        <div style="width: 1078px; height: 0px; border: 1px #F1F5F9 solid"></div>
    }
</div>


   <div style="width: 100vw; margin-top:100px; height: 83px; bottom: 0; position: absolute;">
            <div style="width: 100vw; height: 60px; left: 0px; bottom: 0; position: absolute; background: #338573"></div>
           <div style="width: 459.51px; height: 83px; left: 492.01px; top: 15px; position: absolute; color: white; font-size: 20px; font-family: Poppins; font-weight: 400; line-height: 80px; word-wrap: break-word">© 2023 Freelance Fusion. Designed By Group 1</div>
         </div>

</body>

</html>